CREATE TABLE IF NOT EXISTS roles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  source_type ENUM('jobicy', 'recruiter') NOT NULL,
  source_id VARCHAR(64) NULL,
  source_name VARCHAR(80) NOT NULL,
  source_url VARCHAR(2048) NULL,
  title VARCHAR(180) NULL,
  company_name VARCHAR(180) NULL,
  employment_type VARCHAR(120) NULL,
  location VARCHAR(180) NULL,
  work_mode ENUM('remote', 'hybrid', 'onsite') NULL,
  salary_min DECIMAL(15, 2) NULL,
  salary_max DECIMAL(15, 2) NULL,
  salary_currency CHAR(3) NULL,
  salary_period VARCHAR(40) NULL,
  minimum_experience_months SMALLINT UNSIGNED NULL,
  eligible_countries JSON NULL,
  skills JSON NOT NULL,
  application_url VARCHAR(2048) NULL,
  application_email VARCHAR(254) NULL,
  description MEDIUMTEXT NOT NULL,
  status ENUM('pending', 'published', 'closed') NOT NULL DEFAULT 'pending',
  published_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_roles_source_id (source_type, source_id),
  KEY idx_roles_status_created (status, created_at, id),
  KEY idx_roles_work_mode_location (work_mode, location)
) ENGINE=InnoDB;
